apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: heimdall-templates-dotnet-microservice-host-api
  title: Heimdall dotnet microservice template api host
  description: Retrievs API data for consumer
  tags:
    - dotnet
    - rest
    - aspnetcore
    - openapi
    - microservice
  annotations:
    backstage.io/techdocs-entity: location:default/heimdall-template-dotnet-microservice
spec:
  type: openapi
  lifecycle: production
  owner: devx-maintainers
  system: heimdall-templates-dotnet-microservice
  definition: /swagger/v1/swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: heimdall-templates-dotnet-microservice-host-worker
  title: Heimdall dotnet microservice template event consumer worker host
  description: Retrievs integration events from Kafka topics
  tags:
    - dotnet
    - kafka
    - asyncapi
    - microservice
  annotations:
    backstage.io/techdocs-entity: location:default/heimdall-template-dotnet-microservice
spec:
  type: openapi
  lifecycle: production
  owner: devx-maintainers
  system: heimdall-templates-dotnet-microservice
  definition: /swagger/v1/swagger.json