apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: heimdall-templates-dotnet-microservice
  title: Heimdall dotnet microservice template
  description: This is a system for template in Heimdall for .NET microservice
  tags:
    - dotnet
    - template
    - microservice
  annotations:
    backstage.io/techdocs-entity: location:default/heimdall-template-dotnet-microservice
spec:
  domain: templates-microservice
  owner: devx-maintainers